optimizer: adam
optimizer_params:
  lr: 0.0001

cpg: 
  nb_filter:
  - 10
  filter_len:
  - 2
  pool_len:
  - 2
  activation: relu
  batch_norm: false
  drop_in: 0
  drop_out: 0.2
  l1: 0.001
  l2: 0.001
  nb_hidden: 5

seq: false

# seq: 
  # nb_filter:
  # - 50
  # filter_len:
  # - 10
  # pool_len:
  # - 2
  # activation: relu
  # batch_norm: false
  # drop_in: 0
  # drop_out: 0.2
  # l1: 0.001
  # l2: 0.001
  # nb_hidden: 128

joint: false

target: 
  activation: relu
  batch_norm: false
  drop_out: 0.2
  nb_hidden: 0
  out_activation: sigmoid
